name: Daily App Restart

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          api_token: ${{ secrets.FLY_API_TOKEN }}

      - name: Restart Fly App
        run: fly apps restart blossom-price
