name: Daily pricing notification

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch: {}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ping notification endpoint
        env:
          SESSION_ID: ${{ secrets.PING_SITE_COOKIE  }}
        run: |
          curl -f -X POST "https://bc.pichuhat.dev/api/notify-top-requested" \
            -b "connect.sid=$SESSION_ID" \
            --max-time 30
